# Full list of configuration options: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

output:
  sort-results: true

linters:
  enable:
    - errcheck    # Report unchecked errors
    - gofmt       # Check whether code was gofmt-ed
    - goimports   # Check imports were formatted with gofmt
    - gofumpt     # A stricter gofmt
    - revive      # Broad set of rules; replaces deprecated golint
    - gosimple    # Check whether code can be simplified
    - ineffassign # Detect when assignment to variable is never used
    - misspell    # Report on commonly misspelled English words
    - unconvert   # Remove unnecessary type conversions
    - unparam     # Detect unused function parameters
    - govet       # `go vet`
    - unused      # Detect unused constants/variables/functions/types
    - typecheck   # Ensure code typechecks
    - makezero    # Detect misuse of make with non-zero length and append
    - tenv        # Use testing.(*T).Setenv instead of os.Setenv
    - whitespace  # Report unnecessary blank lines
    - bodyclose   # checks whether HTTP response body is closed successfully
    - gocritic    # More linting
    - promlinter  # Check Prometheus metrics naming via promlint

issues:
  # We want to use our own exclusion rules and ignore all the defaults.
  exclude-use-default: false

  exclude-rules:
    # It's fine if tests ignore errors.
    - path: _test.go
      linters:
        - errcheck
        - bodyclose
        - revive
        - gocritic

  exclude:
    # Ignoring errors on Close, Log, and removing files is OK in most cases.
    - "Error return value of `(.*\\.Close|.*\\.Log|os.Remove)` is not checked"

# Linter settings options: https://golangci-lint.run/usage/linters/
linters-settings:
  whitespace:
    # While there normally shouldn't be extra redundant leading/trailing
    # whitespace, if statement conditions and function headers that cross
    # multiple lines are an exception.
    #
    #   if true ||
    #      false {
    #
    #       // ... ^ must have empty line above
    #    }
    #
    #   func foo(
    #     a int,
    #   ) {
    #
    #     // ... ^ must have empty line above
    #   }
    #
    # This helps readers easily separate where the multi-line if/function ends
    # at a glance.
    multi-if: true
    multi-func: true

  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: argument-limit
        severity: warning
        disabled: false
        arguments: [5]
      - name: banned-characters
        severity: warning
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments: [2]
      - name: function-length
        disabled: true
      - name: line-length-limit
        severity: warning
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: package-comments
        disabled: true
      - name: get-return
        disabled: true
